### ISSUE TITLE
Monero some error happened try again !!!

### ISSUE THREAD

**Issue by ejinbt** [eckmarcommunity/eckmar#112]
can someone help me please

**Comment by ejinbt** [comment]
This is happening when making purchase 
App\Marketplace\Utility\MoneroRPC\Exceptions\RuntimeException: Request have return error: Method not found; Request: {"jsonrpc":"2.0","method":"make_integrated_address","params":{"payment_id":null},"id":1};

**Comment by Gralien** [comment]
are you running wallet cli or rpc wallet? it cant make calls without an rpc
wallet running.
possible timeout? hdd disks are slow and perhaps timeout the request?
This issue has been addressed multiple times.check closed issues please.

**Comment by ejinbt** [comment]
where should i run monero-wallet-rpc . in the host device which the eckmar is hosted or the device i am using to use eckmar

**Comment by Gralien** [comment]
Frome cli on the node

**Comment by ejinbt** [comment]
i opened both monero-wallet-rpc and monerod , changed curl_optimeout . still no luck :(
which one should i pass to .env file in the place of MONERO_HOST, tor address or 127.0.0.1 , my monerod is hosted on tor

**This is the error i get while passing tor address**
pp\Marketplace\Utility\MoneroRPC\Exceptions\RuntimeException: Unable to connect to http://use6iy2rdwigqt2ijjaux22urtkuwtcyxgsf4y3al2sd6uwyx4yf2fqd.onion:18081/json_rpc Error: Could not resolve host: 

the monerod completely works fine when pinged with curl and wallet is connecting to it without any issue

**Comment by Gralien** [comment]
Localhost. Rpc only. Might have to change the timeout in the script?
Especially if using hdd drives

**Comment by ejinbt** [comment]
<img width="444" alt="Screenshot 2024-04-23 at 8 43 33 PM" src="https://github.com/eckmar-community/eckmar/assets/71747409/1b4dee55-e19d-437c-9b2f-ae216053e092">
is this one ? i changed to both 0 and 100

also my monero is in 18081 port , so on env file i should pass 18081 as MONERO_PORT right ? and --rpc-bind-port=18081 on ./monero-wallet-rpc

**Comment by Gralien** [comment]
Have you read your logs?
Cleared cache?

**Comment by ejinbt** [comment]
```
local.ERROR: Request have return error: Method not found; 
Request: {"jsonrpc":"2.0","method":"make_integrated_address","params":{"payment_id":null},"id":1};   

```
it is sending request for daemonRPC , it don't have this method. , walletRPC have this method , should i pass address and port of wallet in .env file ?
when i pass monero-rpc-wallet port , it is showing 
`Unable to connect to http://127.0.0.1:18082/json_rpc Error: Received HTTP/0.9 when not allowed in /var/www/eckmar/app/Marketplace/Utility/MoneroRPC/jsonRPCClient.php`

this is error i am getting on logs

i do this everytime after making changes 
```
php artisan config:clear
php artisan cache:clear
```

also my eckmar is also hosted as onion service

**Comment by jackson-xp** [comment]
It's not your fault; the original code itself doesn't fully support XMR. You'll need to make modifications to the code yourself.

**Comment by ejinbt** [comment]
do you know where exactly i should modify
does eckmar works on bitcoin perfectly?

**Comment by whitevoid90** [comment]
monero works i tested it . did setup the node and the rpc wallet correctly ?

**Comment by jackson-xp** [comment]
> do you know where exactly i should modify does eckmar works on bitcoin perfectly?

"Bitcoin" configuration can run perfectly without any anomalies, but with XMR, I encountered the same error as you did. However, my XMR-cli and RPC nodes are running fine, so I suspect there might be an issue with the backend code (or it could also be a misjudgment). It would be best to seek the help of a PHP programmer to debug this issue.

**Comment by jackson-xp** [comment]
> monero works i tested it . did setup the node and the rpc wallet correctly ?

It's strange that many people seem to encounter this issue, and only a few manage to configure and run it. Have you made any modifications to the native backend code, or did you simply configure the entry point for it to run?
